product: {
  shape: sql_table
  id: int {constraint: primary_key}
  short_name: varchar(255) {constraint: unique}
  title: varchar(255)
  description: text
  owner: int {constraint: foreign_key}
}

team: {
  shape: sql_table
  id: int {constraint: primary_key}
  title: varchar(255) {constraint: unique}
  scrum_master: int
}

user: {
  shape: sql_table
  id: int {constraint: primary_key}
  username: varchar(255) {constraint: unique}
  full_name: varchar(255)
}

sprint: {
  shape: sql_table
  id: int {constraint: primary_key}
  team_id: int {constraint: foreign_key}
}

task_comment: {
  shape: sql_table
  id: int {constraint: primaty_key}
  author: int {constraint: foreign_key}
  task_id: int {constraint: foreign_key}
  content: text
}

team_meeting: {
  shape: sql_table
  id: int {constraint: primary_key}
  title: varchar(255)
  agenda: text
  team_id: int {constraint: foreign_key}
}

team <-> team_meeting.team_id: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one-required
  }
}

sprint.planning_meeting <-> team_meeting: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-one
  }
}

sprint.review_meeting <-> team_meeting: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-one
  }
}

sprint.retro_meeting <-> team_meeting: {
  source-arrowhead: {
    shape: cf-one
  }
  target-arrowhead: {
    shape: cf-one
  }
}

team.daily_meeting <-> team_meeting: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one
  }
}

team_meeting <-> user: {
  label: "participants"
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-many
  }
}

task_comment.task_id <-> task: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one-required
  }
}

task_comment.author <-> user: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one-required
  }
}

team.id <-> sprint.team_id: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
}

team.scrum_master <-> user: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one
  }
}

product.owner <-> user: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one
  }
}

product <-> team: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-many
  }
}

task: {
  shape: sql_table
  id: int {constraint: primary_key}
  type: EPIC | STORY | TASK
  title: varchar(255)
  descripton: text
  product_id: int {constraint: foregign_key}
  part_of: int
}

task.part_of <-> task.id: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-one
  }
}

product.id <-> task.product_id: {
  source-arrowhead: {
    shape: cf-one-required
  }
  target-arrowhead: {
    shape: cf-many
  }
  label: "Product Backlog"
}

sprint.id <-> task.id: {
  source-arrowhead: {
    shape: cf-many
  }
  target-arrowhead: {
    shape: cf-many
  }
  label: "Sprint Backlog"
}

task_changes: {
  shape: sql_table
  task_id: int {constraint: foreign_key}
  field_name: varchar(255)
  previous_value: json
  new_value: json
  changed_by: id {constraint: foreign_key}
  changed_at: timestamp_tz
}

task_changes.task_id <-> task: {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-many
  }
}
task_changes.changed_by <-> user: {
  target-arrowhead: {
    shape: cf-one-required
  }
  source-arrowhead: {
    shape: cf-many
  }
}

