DROP TABLE IF EXISTS task_changes CASCADE;
DROP TABLE IF EXISTS task_relation CASCADE;
DROP TABLE IF EXISTS release_changelog_entry CASCADE;
DROP TABLE IF EXISTS product_teams CASCADE;
DROP TABLE IF EXISTS team_meeting_user CASCADE;
DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS article CASCADE;
DROP TABLE IF EXISTS product_release CASCADE;
DROP TABLE IF EXISTS team_meeting CASCADE;
DROP TABLE IF EXISTS sprint CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

